export const enum BibleName {
  Genesis = 'Genesis',
  Exodus = 'Exodus',
  Leviticus = 'Leviticus',
  Numbers = 'Numbers',
  Deuteronomy = 'Deuteronomy',
  Joshua = 'Joshua',
  Judges = 'Judges',
  Ruth = 'Ruth',
  '1_Samuel' = '1 Samuel',
  '2_Samuel' = '2 Samuel',
  '1_Kings' = '1 Kings',
  '2_Kings' = '2 Kings',
  '1_Chronicles' = '1 Chronicles',
  '2_Chronicles' = '2 Chronicles',
  Ezra = 'Ezra',
  Nehemiah = 'Nehemiah',
  Esther = 'Esther',
  Job = 'Job',
  Psalms = 'Psalms',
  Proverbs = 'Proverbs',
  Ecclesiastes = 'Ecclesiastes',
  Song_of_Solomon = 'Song of Solomon',
  Isaiah = 'Isaiah',
  Jeremiah = 'Jeremiah',
  Lamentations = 'Lamentations',
  Ezekiel = 'Ezekiel',
  Daniel = 'Daniel',
  Hosea = 'Hosea',
  Joel = 'Joel',
  Amos = 'Amos',
  Obadiah = 'Obadiah',
  Jonah = 'Jonah',
  Micah = 'Micah',
  Nahum = 'Nahum',
  Habakkuk = 'Habakkuk',
  Zephaniah = 'Zephaniah',
  Haggai = 'Haggai',
  Zechariah = 'Zechariah',
  Malachi = 'Malachi',

  // New Testament
  Matthew = 'Matthew',
  Mark = 'Mark',
  Luke = 'Luke',
  'John' = 'John',
  Acts = 'Acts',
  Romans = 'Romans',
  '1_Corinthians' = '1 Corinthians',
  '2_Corinthians' = '2 Corinthians',
  Galatians = 'Galatians',
  Ephesians = 'Ephesians',
  Philippians = 'Philippians',
  Colossians = 'Colossians',
  '1_Thessalonians' = '1 Thessalonians',
  '2_Thessalonians' = '2 Thessalonians',
  '1_Timothy' = '1 Timothy',
  '2_Timothy' = '2 Timothy',
  Titus = 'Titus',
  Philemon = 'Philemon',
  Hebrews = 'Hebrews',
  James = 'James',
  '1_Peter' = '1 Peter',
  '2_Peter' = '2 Peter',
  '1_John' = '1 John',
  '2_John' = '2 John',
  '3_John' = '3 John',
  Jude = 'Jude',
  Revelation = 'Revelation',
}

export const enum PlaceStereo {
  parent = 'parent',
  child = 'child',
}

export const enum PlaceType {
  'region' = 'region',
  'settlement' = 'settlement',
}
