export const enum BibleName {
  Genesis = 'Genesis',
  Exodus = 'Exodus',
  Leviticus = 'Leviticus',
  Numbers = 'Numbers',
  Deuteronomy = 'Deuteronomy',
  Joshua = 'Joshua',
  Judges = 'Judges',
  Ruth = 'Ruth',
  '1_Samuel' = '1 Samuel',
  '2_Samuel' = '2 Samuel',
  '1_Kings' = '1 Kings',
  '2_Kings' = '2 Kings',
  '1_Chronicles' = '1 Chronicles',
  '2_Chronicles' = '2 Chronicles',
  Ezra = 'Ezra',
  Nehemiah = 'Nehemiah',
  Esther = 'Esther',
  Job = 'Job',
  Psalms = 'Psalms',
  Proverbs = 'Proverbs',
  Ecclesiastes = 'Ecclesiastes',
  Song_of_Solomon = 'Song of Solomon',
  Isaiah = 'Isaiah',
  Jeremiah = 'Jeremiah',
  Lamentations = 'Lamentations',
  Ezekiel = 'Ezekiel',
  Daniel = 'Daniel',
  Hosea = 'Hosea',
  Joel = 'Joel',
  Amos = 'Amos',
  Obadiah = 'Obadiah',
  Jonah = 'Jonah',
  Micah = 'Micah',
  Nahum = 'Nahum',
  Habakkuk = 'Habakkuk',
  Zephaniah = 'Zephaniah',
  Haggai = 'Haggai',
  Zechariah = 'Zechariah',
  Malachi = 'Malachi',

  // New Testament
  Matthew = 'Matthew',
  Mark = 'Mark',
  Luke = 'Luke',
  'John' = 'John',
  Acts = 'Acts',
  Romans = 'Romans',
  '1_Corinthians' = '1 Corinthians',
  '2_Corinthians' = '2 Corinthians',
  Galatians = 'Galatians',
  Ephesians = 'Ephesians',
  Philippians = 'Philippians',
  Colossians = 'Colossians',
  '1_Thessalonians' = '1 Thessalonians',
  '2_Thessalonians' = '2 Thessalonians',
  '1_Timothy' = '1 Timothy',
  '2_Timothy' = '2 Timothy',
  Titus = 'Titus',
  Philemon = 'Philemon',
  Hebrews = 'Hebrews',
  James = 'James',
  '1_Peter' = '1 Peter',
  '2_Peter' = '2 Peter',
  '1_John' = '1 John',
  '2_John' = '2 John',
  '3_John' = '3 John',
  Jude = 'Jude',
  Revelation = 'Revelation',
}

export enum PlaceStereo {
  parent = 'parent',
  child = 'child',
}

export const enum PlaceType {
  'region' = 'region',
  'settlement' = 'settlement',
}

export enum PlaceSort {
  'like' = 'like',
  'desc' = 'desc',
  'asc' = 'asc',
}

export enum PlaceFilter {
  'like' = 'like',
  'memo' = 'memo',
  'save' = 'save',
}

export enum BibleVersion {
  kor = 'kor',
  niv = 'niv',
  bbe = 'bbe',
  asv = 'asv',
}
export enum BibleBook {
  Gen = 'ge',
  Exod = 'exo',
  Lev = 'lev',
  Num = 'num',
  Deut = 'deu',
  Josh = 'josh',
  Judg = 'jdgs',
  Ruth = 'ruth',
  '1Sam' = '1sm',
  '2Sam' = '2sm',
  '1Kgs' = '1ki',
  '2Kgs' = '2ki',
  '1Chr' = '1chr',
  '2Chr' = '2chr',
  Ezra = 'ezra',
  Neh = 'neh',
  Esth = 'est',
  Job = 'job',
  Ps = 'psa',
  Prov = 'prv',
  Eccl = 'eccl',
  Song = 'ssol',
  Isa = 'isa',
  Jer = 'jer',
  Lam = 'lam',
  Ezek = 'eze',
  Dan = 'dan',
  Hos = 'hos',
  Joel = 'joel',
  Amos = 'amos',
  Obad = 'obad',
  Jonah = 'jonah',
  Mic = 'mic',
  Nah = 'nahum',
  Hab = 'hab',
  Zeph = 'zep',
  Hag = 'hag',
  Zech = 'zec',
  Mal = 'mal',
  Matt = 'mat',
  Mark = 'mark',
  Luke = 'luke',
  John = 'john',
  Acts = 'acts',
  Rom = 'rom',
  '1Cor' = '1cor',
  '2Cor' = '2cor',
  Gal = 'gal',
  Eph = 'eph',
  Phil = 'phi',
  Col = 'col',
  '1Thess' = '1th',
  '2Thess' = '2th',
  '1Tim' = '1tim',
  '2Tim' = '2tim',
  Titus = 'titus',
  Phile = 'phmn',
  Heb = 'heb',
  Jam = 'jas',
  '1Pet' = '1pet',
  '2Pet' = '2pet',
  '1Jn' = '1jn',
  '2Jn' = '2jn',
  '3Jn' = '3jn',
  Jude = 'jude',
  Rev = 'rev',
}
