name: Build & Push API to GHCR

on:
  push:
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # ⚠️ Dockerfile이 ./api에 있다고 가정. (다르면 context를 바꿔)
      - name: Build & Push for linux/amd64
        uses: docker/build-push-action@v6
        with:
          context: . # ✅ 루트에 package.json
          file: ./api/Dockerfile # Dockerfile은 api/에 있음
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/api:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/api:${{ github.sha }}
